# 处理错误

## 基本错误处理

### 需求分析

我们实现了 `ts-axios` 的基础功能，但目前为止我们都是处理了正常接收请求的逻辑，并没有考虑到任何错误情况的处理，这对于一个程序的健壮性而言是远不够的，我们希望程序能捕获到这些错误，做进一步的处理，因此我们这一节需要对 AJAX 各种错误情况做处理。

```typescript
axios({
  method: 'get',
  url: '/error/get'
}).then((res) => {
  console.log(res)
}).catch((e) => {
  console.log(e)
})
```

如果在请求的过程中发生任何错误，我们都可以在 `reject` 回调函数中捕获到。

我们把错误分成了几类，接下来我们就来分别处理这些错误情况。

### 处理网络异常错误

当网络不通的时候发送请求会触发`XMLHttpRequest`对象实例的`error`事件，于是我们可以在`onerror`的事件毁掉函数中捕获此类错误。

`src/xhr.ts`:

```typescript
...
request.onreadystatechange = function handleLoad(){...}
request.onerror = function handleError(){
    reject(new Error(new Error('Network Error'))
}
Object.keys(headers).forEach(...)
...

```



### 处理超时错误

我们可以设置某个请求的超时时间 `timeout`，也就是当请求发送后超过某个时间后仍然没收到响应，则请求自动终止，并触发 `timeout` 事件。

请求默认的超时时间是 0，即永不超时。所以我们首先需要允许程序请求的时候可以配置超时时间,所以我们要在`AxiosRequestConfig `添加`timeout`属性。

`src/types`:

```typescript
export interface AxiosRequestConfig {
  // ...
  timeout?: number
}
```

接着在 `xhr` 函数中添加如下代码：

`src/xhr.ts`:

```typescript
...
const { 
    data = null, 
    url, 
    method = 'get' ,
    headers,
    responseType,
    timeout,
} = config;
...
if(responseType){
    request.responseType = responseType
}
// 添加timeout判断
if(timeout){
    request.timeout = timeout;
}
request.open(method.toUpperCase,url,true);
request.onreadystatechange = function handleLoad(){...}
// 处理网络异常情况
request.onerror = function handleError(){
    reject(new Error(new Error('Network Error'))
}
// 触发ontimeout事件
request.ontimeout = function handleTimeout(){
	reject(new Error(`Timeout of ${time} ms exceeded`))
}
Object.keys(headers).forEach(...)
...

```



### 处理非200状态码

对于一个正常的请求，往往会返回 200-300 之间的 HTTP 状态码，对于不在这个区间的状态码，我们也把它们认为是一种错误的情况做处理。

我们在 `onreadystatechange` 的回调函数中，添加了对`request.status`的判断，因为当出现网络错误或者超时错误的时候，该值都为 0。

我们定义一个函数`handleResponse` 来处理 `request.status` 的值再次判断，如果是 `2xx` 的状态码，则认为是一个正常的请求，否则抛错。

`src/xhr.ts`

```typescript
...
request.onreadystatechange = function handLoad(){
    if(request.readyState !== 4){
        return;
    }
    //当出现网络错误或者超时错误的时候，该值都为 0
    if(request.status === 0){
        return;
    }
    const responseHeaders = request.getAllResponseHeaders();
    const responseData = responseType !== 'text' ? request.response : request.responseText;
    const response:AxiosResponse = {
        data:responseData,
        status:request.status,
        statusText:request.statusText,
        headers:responseHeaders,
        config,
        reqeust
    }
	//让handleResponse 根据response.status的状态码来进行返回response还是抛出错误
    handleResponse(response);

}
...
request.send(data);
function handleResponse(response:AxiosResponse):void{
    if(response.status >=200 && response.status < 300){
        resolve(response)
    }else{
        reject(new Error(`Request failed with status code ${response.status}`))
    }
}
...
```



### 编写验证demo

在 `examples` 目录下创建 `error` 目录，在 `error` 目录下创建 `index.html`:

`examples/error/index.html`:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error example</title>
  </head>
  <body>
    <script src="/__build__/error.js"></script>
  </body>
</html>
```

接着创建 `app.ts` 作为入口文件：

`examples/error/app.ts`:

```js
import axios from '../../src/index'

// 故意把url写错。会报出404错误
axios({
  method: 'get',
  url: '/error/get1'
}).then((res) => {
  console.log(res)
}).catch((e) => {
  console.log(e)
})

// 正常发送请求，不过请求有一定几率会出现错误
axios({
  method: 'get',
  url: '/error/get'
}).then((res) => {
  console.log(res)
}).catch((e) => {
  console.log(e)
})

// 延时5秒，使用chorme Network中的Throttling设置Offline模拟网络环境差
setTimeout(() => {
  axios({
    method: 'get',
    url: '/error/get'
  }).then((res) => {
    console.log(res)
  }).catch((e) => {
    console.log(e)
  })
}, 5000)

// 设置2秒钟超时，后端需要3秒才能返回，所以会触发超时错误
axios({
  method: 'get',
  url: '/error/timeout',
  timeout: 2000
}).then((res) => {
  console.log(res)
}).catch((e) => {
  console.log(e.message)
})
```

接着在 `examples/server.js` 添加新的接口路由：

```typescript
router.get('/error/get', function(req, res) {
   // 使用了随机数来返回正确的样式和错误的样式，多请求几次就能看到正确和错误
  if (Math.random() > 0.5) {
    res.json({
      msg: `hello world`
    })
  } else {
    res.status(500)
    res.end()
  }
})

router.get('/error/timeout', function(req, res) {
  // 使用setTimeout来延时返回，达到请求超时的目的
  setTimeout(() => {
    res.json({
      msg: `hello world`
    })
  }, 3000)
})
```

然后在命令行运行 `npm run dev`，接着打开 chrome 浏览器，访问 `http://localhost:8080/` 即可访问我们的 demo 了，我们点到 `Error` 目录下，通过开发者工具的 network 部分我们可以看到不同的错误情况。

至此我们对各种错误都做了处理，并把它们抛给了程序应用方，让他们对错误可以做进一步的处理。但是这里我们的错误都仅仅是简单的 Error 实例，只有错误文本信息，并不包含是哪个请求、请求的配置、响应对象等其它信息。那么下一节课，我们会对错误信息做增强。



## 错误信息增强

### 需求分析

上一节课我们已经捕获了几类 AJAX 的错误，但是对于错误信息提供的非常有限，我们希望对外提供的信息不仅仅包含错误文本信息，还包括了请求对象配置 `config`，错误代码 `code`，`XMLHttpRequest` 对象实例 `request`以及自定义响应对象 `response`。

这样对于应用方来说，他们就可以捕获到这些错误的详细信息，做进一步的处理。

如下：

```typescript
axios({
  method: 'get',
  url: '/error/timeout',
  timeout: 2000
}).then((res) => {
  console.log(res)
}).catch((e: AxiosError) => {
  console.log(e.message)
  console.log(e.request)
  console.log(e.code)
})
```



### 创建 AxiosError 类

我们先来定义 `AxiosError` 类型接口，用于外部使用。

`src/types/index.ts`：

```typescript
...
// 这里我们要去继承Error对象
export interface AxiosError extends Error{
    isAxiosError:boolean
    config:AxiosRequestConfig
    code?:string|null
    request?:any
    response?:AxiosResponse
}
```

接着我们创建 `src/helpers/error.ts` 文件，然后实现 `AxiosError` 类，它是继承于 `Error` 类。

```typescript
import { AxiosRequestConfig,AxiosResponse } from '../types'
export class AxiosError extends Error{
    isAxiosError:boolean
    config:AxiosRequestConfig
    code?:string|null
    request?:any
    response?:AxiosResponse
    constructor(
        message:string,
        config:AxiosRequestConfig,
        code?:string|null,
        request?:any,
        response?:AxiosResponse
    ){
        //因为继承了父类Error，所以必须要用super调用父类构造函数
        super(message);
        this.config = config
        this.code = code
        this.request = request
        this.response = response
      	this.isAxiosError = true;
        // 当继承js一些内部对象，有可能会出现调用不到自己的方法的情况。所以这段代码就是为了解决这个问题
        Object.setPrototypeOf(this,AxiosError.prototype)
    }
}
```

另外，为了方便使用，我们对外暴露了一个 `createError` 的工厂方法。

`src/helpers/error.ts` 

```typescript
export function createError(
    message:string,
    config:AxiosRequestConfig,
    code?:string|null,
    request?:any,
    response?:AxiosResponse
){
    const error = new AxiosError(message,config,code,request,response);
    return error
}
```



### createError 方法应用

修改关于错误对象创建部分的逻辑，如下：

`src/xhr.ts`:

```typescript
import { createError } from './helpers/error'
...
request.onreadystatechange = function handLoad(){
    if(request.readyState !== 4){
        return;
    }
    //当出现网络错误或者超时错误的时候，该值都为 0
    if(request.status === 0){
        return;
    }
    const responseHeaders = request.getAllResponseHeaders();
    const responseData = responseType !== 'text' ? request.response : request.responseText;
    const response:AxiosResponse = {
        data:responseData,
        status:request.status,
        statusText:request.statusText,
        headers:responseHeaders,
        config,
        reqeust
    }
	//让handleResponse 根据response.status的状态码来进行返回response还是抛出错误
    handleResponse(response);

}

// 处理网络异常情况
request.onerror = function handleError(){
    // 触发了该事件是拿不到response的，所以最后一个参数不会传
    reject(createError('Network Error',config,null,request))
}
// 触发ontimeout事件
request.ontimeout = function handleTimeout(){
    // 触发了该事件是拿不到response的，所以最后一个参数不会传
    reject(createError(`Timeout of ${time} ms exceeded`,config,'ECONNABORTED',request))
}
...
request.send(data);

function handleResponse(response:AxiosResponse):void{
    if(response.status >=200 && response.status < 300){
        resolve(response)
    }else{
        reject(new Error())`Request failed with status code ${response.status}`,config,null,request,response))
    }
}
...
```



### 导出类型定义

在 demo 中，TypeScript 并不能把 `e` 参数推断为 `AxiosError` 类型，于是我们需要手动指明类型，为了让外部应用能引入 `AxiosError` 类型，我们也需要把它们导出。

我们创建 `src/axios.ts` 文件，把之前的 `src/index.ts` 的代码拷贝过去，然后修改 `src/index.ts` 的代码。

完整的 `src/axios.ts`:

```typescript

import {AxiosRequestConfig,AxiosPromise,AxiosResponse} from './types';
import xhr from './xhr';
import {buildRUL} from './helpers/url';
import { transformRequest, transformResponse} from './helpers/data'
import { processHeader } from './helpers/headers'

function axios(config:AxiosRequestConfig):AxiosPromise{
    processConfig(config)
    return xhr(config).then(res => {
    	return transformResponseData(res)
    })
}

// 此方法处理config中的各个参数
function processConfig(config:AxiosRequestConfig):void 
    config.url = transformURL(config);
    // 要先处理headers在去处理data
    config.headers = transformHeaders(config);
    config.data = transformRequestData(config);
}

// 此方法拼接config中url的参数
function transformURL(config:AxiosRequestConfig):string 
    const {url,params} = config;
	return buildURL(url,params);
}

function transformRequestData (config: AxiosRequestConfig): any {
  return transformRequest(config.data)
}

function transformHeaders (config: AxiosRequestConfig): any {
  const { headers={}, data } = config;
  return processHeader(config.data)
}

function transformResponseData(res:AxiosResponse):AxiosResponse{
    res.data = transformResponse(res.data);
    return res;
}

export default axios;
```

`src/index.ts`:

```typescript
import axios from './axios'

// 导出所有类型定义，外部都可以使用这些类型
export * from './types'

export default axios
```

这样我们在 demo 中就可以引入 `AxiosError` 类型了。

`examples/error/app.ts`：

```typescript
import axios, { AxiosError } from '../../src/index'

axios({
  method: 'get',
  url: '/error/timeout',
  timeout: 2000
}).then((res) => {
  console.log(res)
}).catch((e: AxiosError) => {
  console.log(e.message)
  console.log(e.code)
})
```

至此，我们关于 `ts-axios` 的异常处理逻辑就告一段落。下面的章节，我们会对 `ts-axios` 的接口做扩展，让它提供更多好用和方便的 API。